### ISSUE TITLE
no remind tags detected

### ISSUE THREAD

**Issue by uxsdi** [ttscoff/nvremind#2]
Thanks for prompt reply via twitter (@CostasCo)
I am running ruby script in terminal on different folders with .md files containing @remind() tags. Verbose output to terminal returns no tags
Sorry, my fault - misunderstood the concept - tags are detected only for lapsed reminders. So there is no issue here.

**Comment by ttscoff** [comment]
Please post a snippet of one of the files containing @remind tags as well as the command you're running so I can test.

**Comment by uxsdi** [comment]
I've already updated my issue note with apologies - I didn't realised your
script picks reminders after the time specified. I've checked with
different timings - everything works indeed.

Thank you again for prompt reply (as I am depending on your nvALT system in
my daily life)

Regards,
Costa.

**Comment by ttscoff** [comment]
No problem.
