### ISSUE TITLE
Add differential dates

### ISSUE THREAD

**Issue by maelp** [ttscoff/nvremind#5]
Sometimes I don't want to go to the calendar and see what exact date will be on thursday, perhaps a way to solve that would be to allow reminders written like this:

  @remind(+2d 17:00) -- in two days, at 17:00
  @remind(next fri, 17:00) -- next friday, at 17:00  

and the next time the nvremind script is run, it replaces those dates by the exact time where it should be reminded :)

**Comment by ttscoff** [comment]
Or just http://brettterpstra.com/2011/10/15/natural-language-dates-for-textexpander/ :)

It's a good idea, I'll put it in when I get back around to this project.
